dates:
  start: '1980-01-01T00:00:00'
  end: '1980-12-31T23:00:00'
  frequency: 1h
  missing: []
build:
  group_by: 24
statistics:
  allow_nans:
  - svstr
input:
  netcdf:
    path: /lustre/storeB/users/nilsmk/Forcing/nordic4km_stress/n3e5_remake/stress_nora3era5_N4_1980.nc.fixedlatlonuv
    param:
    - svstr